version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REACT_APP_BASE_URL: https://api.staging.blueclerk.com/
        REACT_APP_API_URL: https://api.staging.blueclerk.com/api/v1
        REACT_APP_API_V2_URL: https://api.staging.blueclerk.com/api/v2
        REACT_APP_GOOGLE_APP_ID: 767956916860-kkqvsqniunrhal5j5gco8njs6d0u7t1i.apps.googleusercontent.com
        REACT_APP_FACEBOOK_APP_ID: 490466604947035
        REACT_APP_GOOGLE_KEY: AIzaSyAhohptKzKOOndCrj_6R-gIzYUfMQ3Gs-c
        REACT_APP_SOCKET_URL: https://api.staging.blueclerk.com
        REACT_APP_TELEMETRY_KEY: d9b960bc-cb9a-4b16-b2ac-f2835e70bb65:579855a6-0794-4294-ac6a-456ed85ad093:1980d17
        REACT_APP_LAMBDA_URL: https://api-dev.blueclerk.com/api
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    volumes:
      - .:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
