export const types = {
  'SET_REFRESH_SERVICE_TICKET_STATUS': 'SET_REFRESH_SERVICE_TICKET_STATUS',
  'SET_SERVICE_TICKET': 'SET_SERVICE_TICKET',
  'SET_SERVICE_TICKET_LOADING': 'SET_SERVICE_TICKET_LOADING'
};
