name: Deploy to AWS

on:
  push:
    branches:
      - main  # or your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '19'  # or yourr preferred Node.js version

    - name: Install dependencies
      run: yarn install

    - name: Build
      run: yarn build
      env:
        CI: false  # This prevents treating warnings as errors
        REACT_APP_BASE_URL: ${{ secrets.REACT_APP_BASE_URL }}
        REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
        REACT_APP_API_V2_URL: ${{ secrets.REACT_APP_API_V2_URL }}
        REACT_APP_GOOGLE_APP_ID: ${{ secrets.REACT_APP_GOOGLE_APP_ID }}
        REACT_APP_FACEBOOK_APP_ID: ${{ secrets.REACT_APP_FACEBOOK_APP_ID }}
        REACT_APP_GOOGLE_KEY: ${{ secrets.REACT_APP_GOOGLE_KEY }}
        REACT_APP_SOCKET_URL: ${{ secrets.REACT_APP_SOCKET_URL }}
        REACT_APP_TELEMETRY_KEY: ${{ secrets.REACT_APP_TELEMETRY_KEY }}
        REACT_APP_LAMBDA_URL: ${{ secrets.REACT_APP_LAMBDA_URL }}
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Deploy to S3
      run: aws s3 sync build/ s3://blueclerk-stagging --delete

    - name: Invalidate CloudFront
      run: aws cloudfront create-invalidation --distribution-id E2J1W7PGLLHUBD --paths "/*"
