name: Deploy React App to S3

on:
  push:
    branches:
      - reactupgrade

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Use the latest version

    - name: Setup Node.js
      uses: actions/setup-node@v3  # Use the latest version
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install --legacy-peer-deps

    - name: Build
      run: npm run build

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Replace with your desired AWS region

    - name: Deploy to S3
      run: |
        aws s3 sync build/ s3://blueclerk-react-upgrade-deployment --acl public-read --delete
