name: Deploy React App to S3

on:
  push:
    branches:
      - reactupgrade

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Set up AWS credentials
      run: echo ${{ secrets.AWS_ACCESS_KEY_ID }} > aws_access_key
    - run: echo ${{ secrets.AWS_SECRET_ACCESS_KEY }} > aws_secret_key
    - name: Deploy to S3
      run: |
        aws configure set aws_access_key_id $(cat aws_access_key)
        aws configure set aws_secret_access_key $(cat aws_secret_key)
        aws configure set default.region us-east-1  # Replace with your desired AWS region
        aws s3 sync dist/ s3://blueclerk-react-upgrade-deployment --acl public-read --delete
