name: Deploy React App to S3

on:
  push:
    branches:
      - reactupgrade

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install --legacy-peer-deps

    - name: Add missing Babel plugin
      run: npm install --save-dev @babel/plugin-proposal-private-property-in-object --legacy-peer-deps

    - name: Build with environment variable override
      run: |
        # Set CI to false to avoid treating warnings as errors
        CI=false npm run build

    - name: Deploy React Web to S3 Bucket and Invalidate Cloudfront
      uses: reggionick/s3-deploy@v4
      with:
          folder: build
          bucket: ${{ vars.S3_BUCKET }}
          bucket-region: ${{ vars.AWS_DEFAULT_REGION }}
          dist-id: ${{ vars.DISTRIBUTION_ID }}
          invalidation: '/*'
          no-cache: true
      env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
